### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [tbullock716/prj-rev-bwfs-dasmoto#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good start on this project! The site itself looks great and you did an excellent job keeping the indentation consistent throughout the html. 

Behind the scenes in the css, make sure to keep the css as organized as possible. Consistent spacing and indentation go a long way to avoid frustration down the line. Also in the css, try to always keep in mind DRY principles. Try to set common styling just once for similarly styled elements or sections wherever possible. 

As a next step, try using divs and classes to reinforce the content structure of the page. Sectioning off each content block will help with styling, readability, and creating a well-defined structure for the page. All of these things become more and more crucial as your projects grow in size and complexity.

Keep up the good work!

**Comment by tbullock716** [comment]
Thanks for the feedback! This is really helpful.
